# Generated by Django 5.0.2 on 2025-12-03 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(choices=[('mowing', 'Mowing'), ('edging', 'Edging'), ('weeding', 'Weeding'), ('trimming', 'Trimming'), ('cleanup', 'Clean Up'), ('mulch', 'Mulch'), ('irrigation', 'Irrigation'), ('patios', 'Patios'), ('christmas_lights', 'Christmas Lights'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
