# Generated by Django 5.0.2 on 2025-12-06 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('photo', models.ImageField(help_text='Project photo', upload_to='portfolio/')),
                ('description', models.TextField(blank=True, help_text='Optional project description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this project on the website')),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
